---
title: Handling the Value
order: 2
layout: page
---


[[vaadin-combo-box.value]]
= Handling the Value

== Getting Started

You need to provide the set of items which the user can select with the [propertyname]#items# property.
Current selection is indicated by the [propertyname]#value# and [propertyname]#selectedItem# properties.
You can set or change the selection programmatically by setting the [propertyname]#value# or [propertyname]#selectedItem# property.
Doing so also updates the visible fields.

When setting the items declaratively, notice that the attribute value needs to be a valid JSON string. You need to use single quotes for the attribute value and double quotes inside the value (in the JSON string). Alternatively, you can escape the double quotes inside the value.

[source,html]
----
<vaadin-combo-box
  label="Element"
  items='["Bohrium", "Boron", "Bromine", "Cadmium", "Caesium", "Calcium"]'
  value="Bromine">
</vaadin-combo-box>
----

Setting the items and value programmatically:

[source,javascript]
----
var combobox = document.querySelector('vaadin-combo-box');
combobox.items = ['Bohrium', 'Boron', 'Bromine', 'Cadmium', 'Caesium', 'Calcium'];
combobox.value = 'Bromine';
----

== Events

The [vaadinelement]#vaadin-combo-box# element dispatches events when the selection changes.
An event contains the [propertyname]#value# property in the [propertyname]#event.detail# object.

Since there are two selection properties, namely [propertyname]#value# and [propertyname]#selectedItem#,
an event is fired for each. [propertyname]#value-changed# event contains the selection as a String value,
whereas [propertyname]#selected-item-changed# contains the selection as an Object.

Additionally, a [propertyname]#change# event is fired to match the behavior with <select> element.

[NOTE]
The order in which [propertyname]#value-changed# and [propertyname]#selected-item-changed# events are fired might vary depending on the situation, but
[propertyname]#change# event should always be last.

[source,javascript]
----
var combobox = document.querySelector('vaadin-combo-box');
combobox.addEventListener('value-changed', function(event) {
  console.log(event.detail.value);
});

combobox.addEventListener('selected-item-changed', function(event) {
  console.log(event.detail.value);
});
----

When using the element inside another Polymer element, you can use the declarative binding syntax to subscribe for an event:

[source,html]
----
<dom-module id="my-element">
  <template>
    <vaadin-combo-box on-value-changed="valueChanged"></vaadin-combo-box>
  </template>
</dom-module>
<script>
  Polymer({
    is: 'my-element',
    valueChanged: function(event) {
      alert(event.detail.value);
    }
  });
</script>
----
