name: Boggle Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/boggle/**"
      - .github/workflows/boggle.yml

defaults:
  run:
    working-directory: examples/boggle

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node -g
      - run: ts-node ../../src/cli.ts cloud deploy --appName hathora-boggle --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_ID=fb24d1c82b3c3827cd8ccbe6ff98409778d6b9f5ed39f04e096dffd51c8c9288 ts-node ../../src/cli.ts build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-boggle.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
