name: build
on: [push]
jobs:
  cli-all-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.12.0'
      - run: npm install -g ts-node
      - run: cd examples
      - run: for example in `ls examples`; do pushd $example && ts-node ../../cli.ts && popd; done
