name: build
on: [push]
jobs:
  cli-all-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.12.0'
      - run: npm install
      - run: npm install -g ts-node
      - run: npm test
