name: build
on: [push]
jobs:
  cli-all-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.12.0'
      - run: npm install
      - run: npm install -g ts-node
      - run: |
          cd examples
          pwd
          for example in `ls`; do cd $example && ts-node ../../cli.ts && cd ..; done
