name: Codenames Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/codenames/**"
      - .github/workflows/codenames.yml

defaults:
  run:
    working-directory: examples/codenames

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora -g
      - run: hathora cloud deploy --appName hathora-codenames --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_SECRET=${{ secrets.CODENAMES_APP_SECRET }} hathora build --only client
      - run: cp dist/client/prototype-ui/index.html dist/client/prototype-ui/200.html
      - run: surge dist/client/prototype-ui hathora-codenames.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
