name: Poker Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/poker/**"
      - .github/workflows/poker.yml

defaults:
  run:
    working-directory: examples/poker

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora -g
      - run: hathora cloud deploy --appName hathora-poker --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_SECRET=${{ secrets.POKER_APP_SECRET }} hathora build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-poker.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  frontend-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_SECRET=${{ secrets.POKER_APP_SECRET }} hathora build --only client
      - run: cp dist/client/web/index.html dist/client/web/200.html
      - run: surge dist/client/web screeching-chance.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
