name: Pong Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/pong/**"
      - .github/workflows/pong.yml

defaults:
  run:
    working-directory: examples/pong

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora -g
      - run: hathora cloud deploy --appName hathora-pong --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_SECRET=${{ secrets.PONG_APP_SECRET }} hathora build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-pong.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
