name: Pong Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/pong/**"
      - .github/workflows/pong.yml

defaults:
  run:
    working-directory: examples/pong

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: hathora-cloud deploy --appId app-d6e4a3e0-0a18-4631-9a3a-97ee434e977c --token ${{ secrets.HATHORA_CLOUD_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: HATHORA_APP_ID=app-d6e4a3e0-0a18-4631-9a3a-97ee434e977c ts-node ../../src/cli.ts build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-pong.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
