name: publish

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_extensions: js,jsx,ts,tsx
          auto_fix: true
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
