name: RPS Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/rock-paper-scissor/**"
      - .github/workflows/rock-paper-scissor.yml

defaults:
  run:
    working-directory: examples/rock-paper-scissor

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node -g
      - run: ts-node src/cli.ts cloud deploy --appName hathora-rock-paper-scissor --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install ts-node surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_SECRET=${{ secrets.RPS_APP_SECRET }} ts-node src/cli.ts build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-rock-paper-scissor.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
